# Generated by Django 4.1.5 on 2023-02-02 18:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('dob', models.DateField(verbose_name='DOB')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('ip_number', models.CharField(max_length=50, unique=True, verbose_name='IP Number')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('medical_history', ckeditor.fields.RichTextField(blank=True, verbose_name='Medical History')),
                ('notes', ckeditor.fields.RichTextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='DOC')),
            ],
            options={
                'verbose_name': 'Patient Information',
            },
        ),
    ]
