# Generated by Django 4.1.5 on 2023-02-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('sample_type', models.CharField(choices=[('Biopsy', 'Biopsy'), ('FNAC', 'FNAC')], max_length=50, verbose_name='Sample Type')),
                ('department', models.CharField(choices=[('Ent', 'Ent'), ('Opthalmology', 'Opthalmology'), ('ForensicMedicine', 'Forensic Medicine'), ('GeneralMedicine', 'General Medicine'), ('GS', 'General Surgery'), ('OG', 'O & G'), ('Pe', 'Paediatrics'), ('NS', 'Neurosurgery'), ('N', 'Neurology'), ('P', 'Plastic Surgery'), ('Ur', 'Urology'), ('Ne', 'Paediatrics'), ('NS', 'Neurosurgery')], max_length=100, verbose_name='Department')),
                ('date_arrived', models.DateField(auto_now_add=True)),
                ('procedure_performed', models.TextField(blank=True, max_length=200, verbose_name='Procedure Performed')),
                ('specimen', models.TextField(blank=True, max_length=200, verbose_name='Specimen')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'verbose_name': 'Sample Information',
            },
        ),
    ]
