# Generated by Django 4.1.5 on 2023-02-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='department',
            field=models.CharField(choices=[('Ent', 'Ent'), ('ForensicMedicine', 'Forensic Medicine'), ('GeneralMedicine', 'General Medicine'), ('GS', 'General Surgery'), ('N', 'Neurology'), ('NS', 'Neurosurgery'), ('NS', 'Neurosurgery'), ('OG', 'O & G'), ('Opthalmology', 'Opthalmology'), ('Pe', 'Paediatrics'), ('Ne', 'Paediatrics'), ('P', 'Plastic Surgery'), ('Ur', 'Urology')], max_length=100, verbose_name='Department'),
        ),
    ]
