# Generated by Django 4.1.5 on 2023-02-03 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_alter_sample_sample_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='date_arrived',
        ),
        migrations.AddField(
            model_name='sample',
            name='date_time_arrived',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
