# Generated by Django 4.1.5 on 2023-02-03 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_remove_sample_date_arrived_sample_date_time_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='date_time_arrived',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 18, 35, 36, 655596, tzinfo=datetime.timezone.utc)),
        ),
    ]
