# Generated by Django 4.1.5 on 2023-02-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_alter_sample_date_time_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='unique_specimen_id',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='Specimen Id'),
            preserve_default=False,
        ),
    ]
