# Generated by Django 4.1.5 on 2023-03-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_sample_unique_specimen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='department',
            field=models.CharField(blank=True, choices=[('Ent', 'Ent'), ('ForensicMedicine', 'Forensic Medicine'), ('GeneralMedicine', 'General Medicine'), ('GS', 'General Surgery'), ('N', 'Neurology'), ('NS', 'Neurosurgery'), ('NS', 'Neurosurgery'), ('OG', 'O & G'), ('Opthalmology', 'Opthalmology'), ('Pe', 'Paediatrics'), ('Ne', 'Paediatrics'), ('P', 'Plastic Surgery'), ('Ur', 'Urology')], max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('Biopsy', 'Biopsy'), ('FNAC', 'FNAC')], max_length=50, verbose_name='Sample Type'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='unique_specimen_id',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Specimen Id'),
        ),
    ]
