# Generated by Django 4.1.5 on 2023-02-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'permissions': [('add_associate_approval', 'Can Approve as Associate Prof')], 'verbose_name': 'Approval'},
        ),
    ]
