# Generated by Django 4.1.5 on 2023-02-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
