# Generated by Django 4.1.5 on 2023-02-17 04:40

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to=user.models.User.unique_file_name),
        ),
    ]
